# NumPy Practice 1
Work through each task in order. Try to solve it yourself before looking anything up!

In [1]:
import numpy as np

---
## Level 1 — Basics

### Task 1: Create Arrays
Create the following arrays and print each one:
1. A 1D array of integers from 0 to 9 using `np.arange()`
2. A 1D array of 6 evenly spaced values between 0 and 1 using `np.linspace()`
3. A 3×4 array of all zeros using `np.zeros()`
4. A 2×3 array of all fives (hint: `np.ones()` and multiply, or `np.full()`)

In [8]:
# 1. Integers 0 to 9
np.arange(0,10)

# 2. 6 evenly spaced values between 0 and 1
np.linspace(0,1,6)

# 3. 3x4 array of zeros
np.zeros((3,4))

# 4. 2x3 array of fives
np.ones((2,3))*5


array([[5., 5., 5.],
       [5., 5., 5.]])

### Task 2: Array Properties
A 2D array has been created for you. Inspect it using:
- `.shape` — dimensions
- `.ndim` — number of dimensions
- `.dtype` — data type
- `.size` — total number of elements

**Question to answer:** How many rows and columns does it have? How many elements total?

In [13]:
# Starter data — don't change this
arr = np.array([[3, 1, 4, 1, 5],
                [9, 2, 6, 5, 3],
                [5, 8, 9, 7, 9]])

# Inspect the array
arr.size

15

### Task 3: Indexing & Slicing
Using the same `arr` from Task 2:
1. Get the element in row 1, column 3
2. Get the entire second row
3. Get the entire third column
4. Get the top-right 2×2 subarray (last 2 rows, last 2 columns)

In [20]:
# 1. Element at row 1, column 3
arr[1,3]

# 2. Entire second row
arr[1,:]

# 3. Entire third column

arr[:,2]
# 4. Top-right 2x2 subarray

arr[:2,3:]


array([[1, 5],
       [5, 3]])

---
## Level 2 — Operations

### Task 4: Math & Broadcasting
Two arrays have been created for you.
1. Add, subtract, multiply, and divide `a` and `b` element-wise
2. Multiply every element of `a` by 10 (broadcasting with a scalar)
3. Add the 1D array `bias` to every row of `matrix` (broadcasting with a 2D array)

In [23]:
# Starter data — don't change this
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
bias = np.array([10, 20, 30])

# 1. Element-wise operations on a and b
a+b
a-b
a*b
a/b

# 2. Multiply every element of a by 10
a*10

# 3. Add bias to every row of matrix
matrix + bias

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

### Task 5: Aggregations Along Axes
A 2D array of exam scores has been created (rows = students, columns = subjects).
1. Find the **overall** mean score
2. Find the **mean score per student** (mean across columns, `axis=1`)
3. Find the **mean score per subject** (mean across rows, `axis=0`)
4. Find the highest score overall using `np.max()`

In [29]:
# Starter data — don't change this
# Rows = students, Columns = [Math, English, Science]
scores = np.array([[85, 92, 78],
                   [70, 88, 95],
                   [60, 74, 80],
                   [90, 85, 88]])

# 1. Overall mean
scores.mean()

# 2. Mean per student (axis=1)
scores.mean(1)

# 3. Mean per subject (axis=0)
scores.mean(0)

# 4. Highest score overall
scores.max()

np.int64(95)

In [28]:
scores

array([[85, 92, 78],
       [70, 88, 95],
       [60, 74, 80],
       [90, 85, 88]])

### Task 6: Boolean Masking
Using the same `scores` array from Task 5:
1. Create a boolean mask for all scores **above 80**
2. Use the mask to extract all scores above 80 as a 1D array
3. Count how many scores are above 80 (hint: `True` counts as 1)
4. Replace all scores below 70 with 70 (curve the grades)

In [41]:
# 1. Boolean mask for scores above 80
b = scores>80

# 2. Extract scores above 80
s = scores[b]

# 3. Count how many scores are above 80
b.sum()
# 4. Replace scores below 70 with 70
scores_curved = scores.copy()
scores_curved[scores<70] = 70


In [43]:
scores>80

array([[ True,  True, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

---
## Level 3 — Reshaping & Combining

### Task 7: Reshape & Transpose
1. Create a 1D array of integers from 1 to 12 using `np.arange()`
2. Reshape it into a 3×4 matrix using `.reshape()`
3. Transpose it using `.T`
4. Flatten the transposed array back to 1D using `.flatten()`

In [50]:
# 1. 1D array from 1 to 12

p = np.arange(1,13)
# 2. Reshape to 3x4

p2 = p.reshape([3,4])
# 3. Transpose

p2t = p2.T
# 4. Flatten back to 1D
p2tf = p2t.flatten()


In [51]:
p2tf

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

### Task 8: Stacking Arrays
Three row arrays have been created for you.
1. Stack them **vertically** into a 3×4 matrix using `np.vstack()`
2. Stack `a` and `b` **horizontally** using `np.hstack()`
3. Concatenate all three along `axis=0` using `np.concatenate()`

In [56]:
# Starter data — don't change this
row1 = np.array([1, 2, 3, 4])
row2 = np.array([5, 6, 7, 8])
row3 = np.array([9, 10, 11, 12])

# 1. Stack vertically
np.vstack([row1, row2, row3])

# 2. Stack row1 and row2 horizontally
np.hstack([row1, row2])

# 3. Concatenate all three along axis=0
np.concatenate((row1, row2, row3), axis=0)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Task 9: Random Arrays
1. Set the random seed to `42` using `np.random.seed()`
2. Create a 4×4 matrix of random **integers** between 1 and 100 using `np.random.randint()`
3. Create a 1D array of 5 values from a **normal distribution** (mean=0, std=1) using `np.random.randn()`
4. Randomly **shuffle** the 1D array using `np.random.shuffle()`

In [66]:
# 1. Set random seed
np.random.seed(42)

# 2. 4x4 matrix of random integers 1-100
np.random.randint(1,101,(4,4))

# 3. 5 values from normal distribution
d = np.random.randn(5)
print(d)
# 4. Shuffle the 1D array
np.random.shuffle(d)
print(d)

[-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
[-0.52516981 -2.61254901 -0.92408284 -0.57138017 -0.58087813]


---
## Level 4 — Real-world

### Task 10: Normalize & Analyze Data
A dataset of raw sensor readings has been created for you.

1. Calculate the **mean** and **standard deviation** of the readings
2. **Normalize** the data to a 0–1 range using min-max normalization:
   `normalized = (x - x.min()) / (x.max() - x.min())`
3. Find the **index** of the maximum value using `np.argmax()`
4. Find how many readings are **more than 1 standard deviation above the mean** (use boolean masking)
5. Calculate the **correlation coefficient** between `readings_a` and `readings_b` using `np.corrcoef()`

In [70]:
# Starter data — don't change this
np.random.seed(7)
readings_a = np.random.normal(loc=50, scale=10, size=100)
readings_b = readings_a * 0.8 + np.random.normal(0, 5, 100)  # correlated with a

# 1. Mean and standard deviation of readings_a

readings_a.mean()
readings_a.std()
# 2. Normalize readings_a to 0-1 range

nma = (readings_a - readings_a.min())/(readings_a.max()- readings_a.min())
# 3. Index of the maximum value in readings_a
np.argmax(readings_a)

# 4. Count readings more than 1 std above the mean
m = readings_a>readings_a.mean() + readings_a.std()
m.sum()

# 5. Correlation between readings_a and readings_b
#np.corrcoef(readings_a, readings_b)

np.int64(17)

In [71]:
readings_a.mean()

np.float64(50.120654245177356)

In [72]:
np.mean(readings_a)

np.float64(50.120654245177356)